### ISSUE TITLE
Teams and scoping

### ISSUE THREAD

**Issue by aiwenar** [openstax-poland/adaptarr-server#28]
Implement teams and scope resources to teams.

openstax-poland/adaptarr-backlog#39

**Comment by MartaSztuka** [comment]
Teams and roles are there and can be menage as it should be.
![Screenshot from 2019-10-08 13-43-15](https://user-images.githubusercontent.com/47241114/66393017-becc2f80-e9d1-11e9-9d52-652c31fc2d0f.png)
![Screenshot from 2019-10-08 13-43-22](https://user-images.githubusercontent.com/47241114/66393024-c095f300-e9d1-11e9-93f5-a896ae8767cd.png)
