### ISSUE TITLE
Invalid date for user joined event

### ISSUE THREAD

**Issue by PiotrKozlowski** [openstax-poland/adaptarr-server#47]
`date` for `userjoined` event is wrong / in different format as date for `newmessage` event

```
userjoined date before format 21474836480n
userjoined date formatted Date Sat Jul 06 2650 10:21:20 GMT+0200 (czas środkowoeuropejski letni)
newmessage date before format 1573570073n 
newmessage date formatted Date Tue Nov 12 2019 15:47:53 GMT+0100 (czas środkowoeuropejski standardowy)
```

**Comment by aiwenar** [comment]
This is caused by an incorrect offset when reading the date in [src/api/conversation.ts:118](https://github.com/openstax-poland/adaptarr-front/blob/master/src/api/conversation.ts#L118): date is located at bytes 6 to 14, but is being red from bytes 10 to 18.
